name: Cyclumvitae
favicon: null
layout_spectrum: 0.10799
typography_spectrum: 0.11521
title: Cyclumvitae
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6bb5c0'
    - '#fafcef'
    - '#498a50'
    - '#225127'
    - '#f06e22'
  brandStrength: 0
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0
purpose: []
