name: Cyclumvitae
favicon: null
layout_spectrum: 0.39422
typography_spectrum: 0.70327
title: Cyclumvitae
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0f0e0c'
    - '#332a23'
    - '#738a52'
    - '#a7c282'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
