name: Cyclumvitae
favicon: null
layout_spectrum: 0.7922
typography_spectrum: 0.87931
title: Cyclumvitae
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#2c3a21'
    - '#fef5ec'
    - '#717366'
    - '#a9a9a7'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
