name: Cyclumvitae
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70327
title: Cyclumvitae
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#78b743'
    - '#b55d41'
    - '#ffdd00'
    - '#000000'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
