name: Cyclumvitae
favicon: null
layout_spectrum: 0.2536
typography_spectrum: 0.70327
title: CYCLUMVITAE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b35d41'
    - '#78b744'
    - '#cbcbcb'
    - '#000000'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
