layout_spectrum: 0.018158610677346587
typography_spectrum: 0.6614372923504561
color:
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  brandStrength: 0.4568164472002536
  lightness: 0.3286626075860113
  saturation: 0.848486119415611
  rhythmicContrast: 0.18885910115204751
name: Cyclumvitae
favicon: null
title: Cyclumvitae
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
