name: Cyclumvitae
favicon: null
layout_spectrum: 0.19291696581058204
typography_spectrum: 0.31825275672599673
title: Cyclumvitae
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.48288281774148345
  lightness: 0.7483712495304644
  saturation: 0.05048911273479462
  rhythmicContrast: 0.5579813739750534
purpose: []
